[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.11.4"
hooks = [
  { id = "ruff", args = ["--fix"], files = "^(src|tests)/" },
  { id = "ruff-format", files = "^(src|tests)/" },
]

[[repos]]
repo = "https://github.com/allganize/ty-pre-commit"
rev = "v0.0.17"
hooks = [
  { id = "ty-check", args = ["--python", ".venv"], files = "^(src|tests)/" },
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace", files = "^(src|tests)/" },
  { id = "end-of-file-fixer", files = "^(src|tests)/" },
  { id = "check-yaml", files = "^(src|tests)/" },
  { id = "check-toml", files = "^(src|tests)/" },
]
